"""Page 4 — Preprocessing Planning.

Derives a concrete, orderable preprocessing plan from the Dataset Profile's
per-feature AI observations. Each step's reasoning is generated by the
Groq/LangGraph agent (falls back to local heuristics), and is individually
reviewable and revisable via feedback.
"""
from __future__ import annotations

import streamlit as st

from components import preprocessing_cards, approval
from components.sidebar import render as render_sidebar
from schemas.state import init_session_state
from services.preprocessing_service import PreprocessingService

st.set_page_config(page_title="Preprocessing", page_icon="🧬", layout="wide")
init_session_state()
render_sidebar()

st.title("4️⃣ Preprocessing Planning")
st.caption("Each step below was derived from the approved Dataset Profile's AI observations.")

profile = st.session_state.get("dataset_profile")
if profile is None or not st.session_state.get("approved_experiment_plan"):
    st.warning("Approve the Experiment Plan (Page 3) before planning preprocessing.")
    st.stop()

st.session_state["current_step"] = 3

service = PreprocessingService()

if st.session_state.get("preprocessing_plan") is None:
    with st.spinner("Deriving preprocessing plan from dataset profile..."):
        st.session_state["preprocessing_plan"] = service.build_plan(profile)

plan = st.session_state["preprocessing_plan"]
preprocessing_cards.render(plan, service=service)

if st.button("🔁 Regenerate plan from scratch"):
    st.session_state["preprocessing_plan"] = None
    st.rerun()

approval.render(
    stage_name="Preprocessing Plan",
    approval_key="approved_preprocessing",
    next_step_label="Feature Engineering",
    override_note_key="preprocessing_override_note",
    on_approve=lambda: st.session_state.update(current_step=4),
)

